/**
 * One-time migration script: SQLite → Supabase
 *
 * Reads all data from local SQLite (`data/coliving.db`), transforms
 * JSON strings → parsed objects for JSONB columns, and inserts into
 * Supabase preserving original IDs (for FK integrity).
 *
 * Uses raw SQL via supabase.rpc to support OVERRIDING SYSTEM VALUE
 * for GENERATED ALWAYS AS IDENTITY columns.
 *
 * Run with: bun --env-file=.env.local scripts/migrate-to-supabase.ts
 */

import { Database } from "bun:sqlite";
import { createClient } from "@supabase/supabase-js";
import { join } from "path";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in env. Set them in .env.local and run:");
  console.error("  bun --env-file=.env.local scripts/migrate-to-supabase.ts");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

const DB_DIR = process.env.DB_PATH || join(process.cwd(), "data");
const DB_PATH = join(DB_DIR, "coliving.db");
const db = new Database(DB_PATH, { readonly: true });

function parseJsonField(raw: string | null): unknown {
  if (!raw) return null;
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

// Escape a value for SQL insertion
function sqlValue(val: unknown): string {
  if (val === null || val === undefined) return "NULL";
  if (typeof val === "number") return String(val);
  if (typeof val === "object") return `'${JSON.stringify(val).replace(/'/g, "''")}'::jsonb`;
  return `'${String(val).replace(/'/g, "''")}'`;
}

async function runSQL(sql: string): Promise<void> {
  const resp = await fetch(`${SUPABASE_URL}/rest/v1/rpc/`, {
    method: "POST",
    headers: {
      apikey: SUPABASE_SERVICE_KEY!,
      Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({}),
  });
  // rpc endpoint won't work for raw SQL — use the pg endpoint instead
  // Actually, let's use the Supabase SQL endpoint (management API)
  throw new Error("Not used");
}

async function migrateTable(
  tableName: string,
  rows: Record<string, unknown>[],
): Promise<number> {
  if (rows.length === 0) {
    console.log(`  ${tableName}: 0 rows (empty)`);
    return 0;
  }

  // Build INSERT statements with OVERRIDING SYSTEM VALUE
  const columns = Object.keys(rows[0]);

  // Insert row by row to handle errors gracefully
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const values = columns.map((col) => sqlValue(row[col]));
    const sql = `INSERT INTO ${tableName} (${columns.join(", ")}) OVERRIDING SYSTEM VALUE VALUES (${values.join(", ")})`;

    // Use the Supabase management API to run raw SQL
    const resp = await fetch(`${SUPABASE_URL}/rest/v1/rpc/exec_sql`, {
      method: "POST",
      headers: {
        apikey: SUPABASE_SERVICE_KEY!,
        Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query: sql }),
    });

    if (!resp.ok) {
      // exec_sql RPC doesn't exist by default, fall back to individual inserts without id
      throw new Error(`exec_sql not available: ${await resp.text()}`);
    }
  }

  console.log(`  ${tableName}: ${rows.length} rows migrated`);
  return rows.length;
}

async function main() {
  console.log("═══ Fruitful Rooms: SQLite → Supabase Migration ═══\n");
  console.log(`Source: ${DB_PATH}`);
  console.log(`Target: ${SUPABASE_URL}\n`);

  // First, create a helper function in Supabase to execute raw SQL
  console.log("─── Creating exec_sql helper function ───");

  // We'll use the Supabase REST API to create the function via a direct POST
  // Actually — the simplest approach: use fetch to the Supabase SQL API
  // The management API is at https://api.supabase.com but needs a different token

  // Better approach: create exec_sql function first, then use it
  // But we can't create it without running SQL...

  // Simplest working approach: use the service role key to insert WITHOUT the id column,
  // letting Supabase auto-generate IDs, then we just need to ensure FK references
  // are consistent by inserting in order and mapping old IDs to new IDs.

  // Actually, the BEST approach: ask Juan to run one SQL command first, OR
  // we create the function via the Supabase Dashboard SQL Editor approach.

  // Let's try a different approach: use the supabase-js client but delete and
  // re-create the identity columns as GENERATED BY DEFAULT instead of ALWAYS.

  // SIMPLEST FIX: Create an exec_sql RPC function
  console.log("  Creating exec_sql function via Supabase RPC...");

  // We need to first get this function created. Let's try using the existing
  // connection via the PostgREST API with a specially crafted request.

  // The real solution: output SQL INSERT statements for Juan to paste,
  // OR change the column definition to GENERATED BY DEFAULT.

  // Let's use the approach that actually works: alter the identity columns
  // to GENERATED BY DEFAULT, insert with explicit IDs, then alter back.

  // Step 1: Create a helper SQL function that Juan pastes once
  console.log("\n⚠️  One-time setup needed!");
  console.log("  Paste this in the Supabase SQL Editor and run it:\n");
  console.log(`CREATE OR REPLACE FUNCTION exec_sql(query TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  EXECUTE query;
END;
$$;`);
  console.log("\n  Then re-run this migration script.");
  console.log("  Checking if exec_sql already exists...\n");

  // Test if exec_sql exists
  const testResp = await fetch(`${SUPABASE_URL}/rest/v1/rpc/exec_sql`, {
    method: "POST",
    headers: {
      apikey: SUPABASE_SERVICE_KEY!,
      Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query: "SELECT 1" }),
  });

  if (!testResp.ok) {
    const err = await testResp.text();
    if (err.includes("Could not find") || err.includes("404") || err.includes("does not exist")) {
      console.error("  ✗ exec_sql function not found. Please create it first (see SQL above).");
      process.exit(1);
    }
    console.error("  ✗ Unexpected error:", err);
    process.exit(1);
  }

  console.log("  ✓ exec_sql function exists!\n");

  console.log("─── Migrating tables ───");

  // Helper to run SQL via exec_sql RPC
  async function sql(query: string): Promise<void> {
    const resp = await fetch(`${SUPABASE_URL}/rest/v1/rpc/exec_sql`, {
      method: "POST",
      headers: {
        apikey: SUPABASE_SERVICE_KEY!,
        Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query }),
    });
    if (!resp.ok) {
      const text = await resp.text();
      throw new Error(`SQL error: ${text}\nQuery: ${query.slice(0, 200)}`);
    }
  }

  // Migrate each table
  const tables = [
    {
      name: "properties",
      transform: (row: Record<string, unknown>) => ({ ...row }),
    },
    {
      name: "rooms",
      transform: (row: Record<string, unknown>) => ({
        ...row,
        amenities: parseJsonField(row.amenities as string | null),
        photos: parseJsonField(row.photos as string | null),
      }),
    },
    {
      name: "tenants",
      transform: (row: Record<string, unknown>) => ({ ...row }),
    },
    {
      name: "inquiries",
      transform: (row: Record<string, unknown>) => ({ ...row }),
    },
    {
      name: "payments",
      transform: (row: Record<string, unknown>) => ({ ...row }),
    },
    {
      name: "expenses",
      transform: (row: Record<string, unknown>) => ({ ...row }),
    },
  ];

  const counts: Record<string, number> = {};

  for (const table of tables) {
    const rows = db.query(`SELECT * FROM ${table.name} ORDER BY id`).all() as Record<string, unknown>[];
    if (rows.length === 0) {
      console.log(`  ${table.name}: 0 rows (empty)`);
      counts[table.name] = 0;
      continue;
    }

    const transformed = rows.map(table.transform);
    const columns = Object.keys(transformed[0]);

    // Build a multi-row INSERT with OVERRIDING SYSTEM VALUE
    // Do batches of 50 to avoid huge payloads
    const batchSize = 50;
    for (let i = 0; i < transformed.length; i += batchSize) {
      const batch = transformed.slice(i, i + batchSize);
      const valueRows = batch.map((row) => {
        const vals = columns.map((col) => sqlValue(row[col]));
        return `(${vals.join(", ")})`;
      });

      const insertSql = `INSERT INTO ${table.name} (${columns.join(", ")}) OVERRIDING SYSTEM VALUE VALUES ${valueRows.join(", ")}`;
      await sql(insertSql);
    }

    console.log(`  ${table.name}: ${rows.length} rows migrated`);
    counts[table.name] = rows.length;
  }

  // Reset identity sequences
  console.log("\n─── Resetting identity sequences ───");
  for (const table of tables) {
    const localMax = db.query(`SELECT MAX(id) as max_id FROM ${table.name}`).get() as { max_id: number | null };
    if (localMax.max_id) {
      await sql(`SELECT setval(pg_get_serial_sequence('${table.name}', 'id'), ${localMax.max_id})`);
      console.log(`  ${table.name} sequence reset to ${localMax.max_id + 1}`);
    }
  }

  // Verify counts
  console.log("\n─── Verifying row counts ───");
  let allGood = true;
  for (const [tableName, expected] of Object.entries(counts)) {
    const { count, error } = await supabase
      .from(tableName)
      .select("*", { count: "exact", head: true });

    if (error) {
      console.error(`  ERROR verifying ${tableName}:`, error.message);
      allGood = false;
      continue;
    }

    const ok = count === expected;
    console.log(`  ${tableName}: ${count}/${expected} ${ok ? "✓" : "✗ MISMATCH"}`);
    if (!ok) allGood = false;
  }

  console.log(`\n${allGood ? "✓ Migration complete!" : "✗ Some tables have mismatches — review above."}`);
}

main().catch(console.error);
